### ISSUE TITLE
Brush animations in first-person are broken

### ISSUE THREAD

**Issue by raspmary** [min2222/Archaeology-API#1]
brush holding position/animations in first-person seem incorrect
this issue occurs even when no other mods are present

https://github.com/min2222/Archaeology-API/assets/130072888/28a2f40f-bbf8-4c1c-b8f9-2993216dc417

**Comment by JustVibin247** [comment]
I second this issue, as I seem to be experiencing the same thing.

**Comment by min2222** [comment]
fixed
