### ISSUE TITLE
Trail ruins and ocean ruins have no suspicious gravel/sand

### ISSUE THREAD

**Issue by raspmary** [min2222/Archaeology-API#2]
both types of ocean ruins and trail ruins contain no suspicious blocks of any kind
desert pyramids and desert wells do have their suspicious sand as intended

**Comment by JustVibin247** [comment]
Also same issue here lol.

**Comment by min2222** [comment]
well, actually no idea why it doesn't work

**Comment by JustVibin247** [comment]
Did you add any code that handles sus gravel generation in the trail ruins? Because I know that sus gravel in trail ruins is randomly generated and not saved to the structure files.

**Comment by min2222** [comment]
didn't knew it thanks for information!

**Comment by SiverDX** [comment]
it is kinda part of the structure file / specification
handled by processors

e.g. https://github.com/misode/mcmeta/blob/1.20.1-data/data/minecraft/worldgen/processor_list/trail_ruins_houses_archaeology.json

and you already have these
but it seems like you're missing the block tag `minecraft:trail_ruins_replaceable`

**Comment by JustVibin247** [comment]
Still not working after the newest update.

**Comment by JustVibin247** [comment]
Wait hold on, I accidentally had 2 version of the mod in my folder.

**Comment by JustVibin247** [comment]
Testing to see if that was the reason.

**Comment by SiverDX** [comment]
prob still wont work, the processor is in 1.20 format and its process method is not being called at all
