### ISSUE TITLE
Crash while exploring ocean

### ISSUE THREAD

**Issue by vivagabe** [min2222/Archaeology-API#3]
Im not 100% sure the issue is with Archaeology API but i know that if i remove it, theres no more crashing.
[crash-2023-12-30_23.05.42-server.txt](https://github.com/min2222/Archaeology-API/files/13800469/crash-2023-12-30_23.05.42-server.txt)

Thank you!

**Comment by kitovoi111** [comment]
Too problem

**Comment by kitovoi111** [comment]
[crash-2023-12-31_10.22.04-server.txt](https://github.com/min2222/Archaeology-API/files/13800499/crash-2023-12-31_10.22.04-server.txt)

**Comment by kitovoi111** [comment]
![image](https://github.com/min2222/Archaeology-API/assets/147491823/affb3d4e-ce74-442b-aba8-25c5798023eb)
