### ISSUE TITLE
Brushing suspicious blocks does not show item being uncovered

### ISSUE THREAD

**Issue by JustVibin247** [min2222/Archaeology-API#8]
Just as the title says. When brushing a suspicious block, the uncovering animation does not play. So you cannot see what item you will get when brushing.
![2024-02-27_10 34 31](https://github.com/min2222/Archaeology-API/assets/72247863/d72885c8-5a8d-4956-abee-b103d8dcdbbc)

**Comment by min2222** [comment]
should fixed in latest release
